version: "3.7"

services:
  gitlab:
    image: gitlab/gitlab-ce:17.2.1-ce.0@sha256:9a5dff8bec16a32551b2069de505be134b30024e022ee72f30d0eddb9cccac95
    container_name: gitlab
    restart: unless-stopped
    hostname: 'http://${DEVICE_DOMAIN_NAME}:8929'
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        gitlab_root_password=${APP_PASSWORD}
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        nginx['listen_port'] = 8929
        nginx['listen_https'] = false
    ports:
      - '8929:8929'
      - '2424:22'
    volumes:
      - ${APP_DATA_DIR}/data/config:/etc/gitlab
      - ${APP_DATA_DIR}/data/logs:/var/log/gitlab
      - ${APP_DATA_DIR}/data/data:/var/opt/gitlab
    shm_size: '256m'